### ISSUE TITLE
 how to transform the result of query to use it in anothers

### ISSUE THREAD

**Issue by jcamilo97** [haoliangyu/pg-reactive#5]
hello, I am trying to transform the result into the first query and then use it in the next query
```javascript
let devolution;   
let one = pgrx.query('UPDATE public.appoinment SET status=$1 WHERE id_appoinment = $2 RETURNING date;', [status, id_appointment])
      .do((result) =>{
        let start_actual_time = Math.round(new Date().getTime()/1000.0)
        let end_actual_time = Math.round(new Date(result.date).getTime()/1000.0);
        let diff = end_actual_time - start_actual_time;      
        if(diff > 86400){
           devolution = 1;
        } else if(diff > 18000){
          devolution = 0.5;
        }else if(diff > 0) {
          devolution = 0;
        } 
      })
      .mergeMap((response) => {
        return pgrx.query('INSERT INTO refund(fk_payment, date, amount, percentage) values ((select id_payment from payment where fk_appoinment = $1) , now(), ((select cast (ammount AS INT ) from payment where fk_appoinment = $2), $3);', [id_appointment,id_appointment, devolution] ); 
      }) ```

**Comment by haoliangyu** [comment]
In your code, the `response` in the `mergeMap` operator is from the first database query. You have two ways to solve this:

* Declare `start_actual_time`, `end_actual_time`, and `devolution` outside the handler function of `do` operator. This will make them accessible to the handler function of `mergeMap` operator.

* Use [map](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-map) instead of `do` to execute the transformation and return the result for next operator (`mergeMap`).

**Comment by jcamilo97** [comment]
Great, thank you very much.
